server:
  port: 9000
spring:
  application:
    name: ad-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/

zuul:
  prefix: /pyp
  routes:
    sponsor:
      path: /pyp-sponsor/**
      serviceId: pyp-ad-sponsor
      strip-prefix: false
    search:
      path: /pyp-search/**
      serviceId: pyp-ad-search
      strip-prefic: false
